# Generated by Django 3.1.7 on 2021-03-11 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0003_auto_20210311_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_path', models.CharField(max_length=256)),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acount.userinfo')),
            ],
        ),
    ]
