# Generated by Django 3.1.7 on 2021-03-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0004_userava'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userava',
            name='u',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='acount.userinfo'),
        ),
    ]
