# Generated by Django 3.1.7 on 2021-03-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0009_auto_20210312_2134'),
    ]

    operations = [
        migrations.CreateModel(
            name='cls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('people', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('age', models.IntegerField()),
                ('in_date', models.DateField(auto_now_add=True)),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')])),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='acount.cls')),
            ],
        ),
        migrations.AddField(
            model_name='cls',
            name='t',
            field=models.ManyToManyField(to='acount.teacher'),
        ),
    ]
