# Generated by Django 3.1.7 on 2021-03-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acount', '0012_auto_20210312_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cls',
            name='people',
        ),
    ]
