# Generated by Django 3.1.7 on 2021-03-12 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210312_2128'),
        ('main', '0003_auto_20210312_2136'),
    ]

    operations = [
    ]
